Task 3 Tree Node.js File System
nagraiv/graivoronskaya-otus pull request #2
Opened 2023-10-16 16:10 UTC by nagraiv

Скрипт для вывода списка файлов и папок файловой системы. Запуск из CLI:
node index.js <путь к папке> [--depth <глубина рекурсии>]

2023-10-20 19:40 UTC, nlapshin requested changes

2023-10-20 19:40 UTC, nlapshin commented on 3_file_sys/index.js
> +    .option('-d, --depth <number>', 'A depth of recursive directory visit');
Можете сюда докинуть дефолтное значение, например, 1.

2023-10-20 19:40 UTC, nlapshin commented on 3_file_sys/makeFileTree.js
> +    let currentDepth = depth ?? 100;
А в чем смысл этого, не до конца понятно.

2023-10-20 19:40 UTC, nlapshin commented on 3_file_sys/makeFileTree.js
> +            }
Я бы тихо не скрывал ошибки, возможно там есть специального типа файл, можно пропустить ошибку в реальных приложениях

2023-10-22 14:54 UTC, nagraiv commented on 3_file_sys/makeFileTree.js
> +    let currentDepth = depth ?? 100;
let currentDepth = depth ?? 100;
currentDepth - предел глубины реккурсии, уменьшается при каждом рекурсивном вызове.
Выход из рекурсии происходит при отсутствии вложенных файлов, либо если мы достигли предельной глубины и currentDepth стало равным 0
Если изначально в нашу функцию не было передано предела глубины рекурсивного обхода, то устанавливаем предел 100. Мне показалось это значение достаточным.

2023-10-22 14:56 UTC, nagraiv commented on 3_file_sys/makeFileTree.js
> +            }
Раскоментила

2023-10-22 15:20 UTC, nagraiv commented on 3_file_sys/index.js
> +    .option('-d, --depth <number>', 'A depth of recursive directory visit');
Добавила значение по умолчанию = 5.

2023-10-29 16:08 UTC, merged